import psycopg2 as dbapi2
import app

INIT_STATEMENTS = [
    """CREATE TABLE IF NOT EXISTS DORMADMIN (
    id SERIAL PRIMARY KEY,
    email VARCHAR(40) UNIQUE NOT NULL,
    pword TEXT NOT NULL
    )""",

    """CREATE TABLE IF NOT EXISTS SUPERVISOR (
    id SERIAL PRIMARY KEY,
    firstname VARCHAR(30) NOT NULL,
    surname VARCHAR(30) NOT NULL,
    email VARCHAR(40) UNIQUE NOT NULL,
    pword TEXT NOT NULL,
    phonenum VARCHAR(20) UNIQUE
    )""",

    """CREATE TABLE IF NOT EXISTS BUILDING (
    id SERIAL PRIMARY KEY,
    supervisorid INTEGER REFERENCES SUPERVISOR(id),
    dormname VARCHAR(255) NOT NULL,
    dormdescription VARCHAR(255),
    picture BYTEA
    )""",

    """CREATE TABLE IF NOT EXISTS ROOM (
    id SERIAL PRIMARY KEY,
    buildingid INTEGER NOT NULL REFERENCES BUILDING(id),
    capacity INTEGER NOT NULL,
    allotment INTEGER DEFAULT 0,
    roomdescription VARCHAR(255),
    picture BYTEA
    )""",

    """CREATE TABLE IF NOT EXISTS STUDENT (
    id SERIAL PRIMARY KEY,
    roomno INTEGER REFERENCES ROOM(id),
    firstname VARCHAR(30) NOT NULL,
    surname VARCHAR(30) NOT NULL,
    date_of_birth TIMESTAMP NOT NULL,
    date_of_entrance TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    phonenum VARCHAR(20),
    email VARCHAR(40) UNIQUE NOT NULL,
    pword TEXT NOT NULL
    )""",

    """CREATE TABLE IF NOT EXISTS PAYMENT (
    studentid INTEGER NOT NULL REFERENCES STUDENT(id),
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (studentid, payment_date),
    roomno INTEGER NOT NULL REFERENCES room(id),
    receipt_file BYTEA,
    is_approved BOOLEAN DEFAULT 'false'
    )""",

    """CREATE TABLE IF NOT EXISTS COMPLAINT(
    id SERIAL PRIMARY KEY,
    studentid INTEGER NOT NULL REFERENCES STUDENT(id),
    supervisorid INTEGER NOT NULL REFERENCES SUPERVISOR(id),
    complaint VARCHAR(255),
    response VARCHAR(255),
    is_responded BOOLEAN DEFAULT 'false'
    )""",

    """CREATE TABLE IF NOT EXISTS REQUEST (
    request_id SERIAL PRIMARY KEY,
    studentid INTEGER NOT NULL REFERENCES STUDENT(id),
    buildingno INTEGER NOT NULL REFERENCES BUILDING(id)
    )""",

    """INSERT INTO dormadmin(email, pword) VALUES
    ('ituyurtlariyonetici@itu.edu.tr', 'f94ddb1020852cf6b88e5738ed0b07b9c29bdf5522e6077069e3059aa7433021')""",
    """INSERT INTO building(dormname) VALUES ('ITU VADİ DORMS #1')""",
    """INSERT INTO building(dormname) VALUES ('ITU VADİ DORMS #2')""",
    """INSERT INTO building(dormname) VALUES ('ITU VADİ DORMS #3')""",
    """INSERT INTO building(dormname) VALUES ('ITU VADİ DORMS #4')""",
    """INSERT INTO building(dormname) VALUES ('ITU MEZUNLAR DORMS #1')""",
    """INSERT INTO building(dormname) VALUES ('ITU MEZUNLAR DORMS #2')""",
    """INSERT INTO building(dormname) VALUES ('ITU MEZUNLAR DORMS #3')""",
    """INSERT INTO building(dormname) VALUES ('ITU MEZUNLAR DORMS #4')""",
    """INSERT INTO building(dormname) VALUES ('ITU GÖLET DORMS #1')""",
    """INSERT INTO building(dormname) VALUES ('ITU GÖLET DORMS #2')""",
    """INSERT INTO building(dormname) VALUES ('ITU GÖLET DORMS #3')""",
    """INSERT INTO building(dormname) VALUES ('ITU GÖLET DORMS #4')""",
    """INSERT INTO building(dormname) VALUES ('ITU GÖLET DORMS #5')""",
    """INSERT INTO building(dormname) VALUES ('ITU GÖLET DORMS #6')""",
    """INSERT INTO building(dormname) VALUES ('ITU GÖLET DORMS #7')""",
    """INSERT INTO building(dormname) VALUES ('ITU GÖLET DORMS #8')""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (1,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (2,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (3,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (4,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (5,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (5,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (5,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (5,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (5,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (5,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (5,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (5,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (5,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (5,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (5,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (5,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (5,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (6,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (6,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (6,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (6,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (6,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (6,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (6,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (6,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (6,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (6,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (6,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (6,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (6,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (7,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (7,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (7,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (7,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (7,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (7,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (7,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (7,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (7,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (7,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (7,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (7,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (7,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES (8,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (8,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (8,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (8,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (8,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES (8,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (8,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (8,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (8,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES (8,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (8,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (8,4)""",
    """INSERT INTO room(buildingid, capacity) VALUES (8,5)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (9,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (10,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (11,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (12,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (13,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (14,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (15,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,1)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,2)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,3)""",
    """INSERT INTO room(buildingid, capacity) VALUES  (16,3)""",
]


def initialize(url):
    with dbapi2.connect(url) as connection:
        cursor = connection.cursor()
        for statement in INIT_STATEMENTS:
            cursor.execute(statement)
        cursor.close()


if __name__ == "__main__":
    if app.ENV == 'DEV':
        url = "postgres://postgres:admin@localhost:5432/dorms"
    else:
        url ='postgres://xmumbtkwyfnwjw:f6b558df185eb87ebb43097a973d453d72e56112d28431d9867ab967ad686ef9@ec2-34-230-149-169.compute-1.amazonaws.com:5432/d2p706ei2cossa'
    initialize(url)
